(#46) Create reusable Elasticsearch health check.
- Add general usge instructions to README.md

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -113,16 +113,6 @@ jobs:
               ## Create test output and API logging location
               mkdir -p integration-tests/target
 
-      - name: Load Data into elasticsearch & prepare for tests
-        env:
-          ELASTIC_SEARCH_HOST: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
-        run: |
-              ## Create test output and API logging location
-              mkdir -p integration-tests/target
-
-              ## Load the elasticsearch data
-              ./integration-tests/bin/load-integration-data.sh
-
         # This project doesn't create an API as a deliverable artifact. In order to test the shared
         # API components, we have to create an API specifically for testing, which means it also has
         # to be built for the express purpose of running the integration tests.
@@ -163,6 +153,30 @@ jobs:
 
               echo "API is up"
 
+      - name: Run tests requiring no data be present.
+        ## Normally bash runs with -e which exits the shell upon hitting
+        ## an error which breaks our ability to capture those errors.
+        shell: bash --noprofile --norc -o pipefail {0}
+        run: |
+              ## Run Karate
+              cd integration-tests && ./bin/karate ./pre-data-features
+
+              ## Store the exit code off so we can pass this step and
+              ## capture the test output in the next step, but still
+              ## fail the entire job
+              echo TEST_EXIT_CODE_1=$? >> $GITHUB_ENV
+              exit 0
+
+      - name: Load Data into elasticsearch & prepare for tests
+        env:
+          ELASTIC_SEARCH_HOST: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
+        run: |
+              ## Create test output and API logging location
+              mkdir -p integration-tests/target
+
+              ## Load the elasticsearch data
+              ./integration-tests/bin/load-integration-data.sh
+
       - name: Run Integration Test
         ## Normally bash runs with -e which exits the shell upon hitting
         ## an error which breaks our ability to capture those errors.
@@ -174,7 +188,7 @@ jobs:
               ## Store the exit code off so we can pass this step and
               ## capture the test output in the next step, but still
               ## fail the entire job
-              echo TEST_EXIT_CODE=$? >> $GITHUB_ENV
+              echo TEST_EXIT_CODE_2=$? >> $GITHUB_ENV
               exit 0
 
       - name: Upload Integration test results
@@ -186,7 +200,7 @@ jobs:
       - name: Fail build on bad tests
         run: |
               ## Check if we had errors on the test step, and if so, fail the job
-              if [ $TEST_EXIT_CODE -ne 0 ]; then
+              if [ $TEST_EXIT_CODE_1 -ne 0 ] || [ $TEST_EXIT_CODE_2 -ne 0 ]; then
                 echo "Tests Failed -- See Run Integration Test step or integration-test-results artifact for more information"
                 exit $TEST_EXIT_CODE
               else
